In [1]:
import pandas as pd

In [2]:
import duckdb

In [5]:
df = pd.read_csv("Steel_industry_data.csv")

In [6]:
duckdb.sql("""
SELECT *
From df
LIMIT 10
""").df()

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_of_week,Load_Type
0,01/01/2018 00:15,3.17,2.95,0.0,0.0,73.21,100.0,900,Weekday,Monday,Light_Load
1,01/01/2018 00:30,4.00,4.46,0.0,0.0,66.77,100.0,1800,Weekday,Monday,Light_Load
2,01/01/2018 00:45,3.24,3.28,0.0,0.0,70.28,100.0,2700,Weekday,Monday,Light_Load
3,01/01/2018 01:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,Weekday,Monday,Light_Load
4,01/01/2018 01:15,3.82,4.50,0.0,0.0,64.72,100.0,4500,Weekday,Monday,Light_Load
5,01/01/2018 01:30,3.28,3.56,0.0,0.0,67.76,100.0,5400,Weekday,Monday,Light_Load
6,01/01/2018 01:45,3.60,4.14,0.0,0.0,65.62,100.0,6300,Weekday,Monday,Light_Load
7,01/01/2018 02:00,3.60,4.28,0.0,0.0,64.37,100.0,7200,Weekday,Monday,Light_Load
8,01/01/2018 02:15,3.28,3.64,0.0,0.0,66.94,100.0,8100,Weekday,Monday,Light_Load
9,01/01/2018 02:30,3.78,4.72,0.0,0.0,62.51,100.0,9000,Weekday,Monday,Light_Load

In [9]:
duckdb.sql("""
SELECT
    Usage_kWh,
    Load_type,
    Day_of_week
FROM df
WHERE Usage_kWh > 100
ORDER BY Usage_kWh DESC
""").df()

      Usage_kWh     Load_Type Day_of_week
0        157.18   Medium_Load    Thursday
1        153.14   Medium_Load      Monday
2        151.67  Maximum_Load     Tuesday
3        151.31   Medium_Load      Friday
4        149.65  Maximum_Load    Thursday
...         ...           ...         ...
1677     100.08  Maximum_Load   Wednesday
1678     100.08    Light_Load   Wednesday
1679     100.08   Medium_Load   Wednesday
1680     100.01  Maximum_Load    Thursday
1681     100.01   Medium_Load    Saturday

[1682 rows x 3 columns]

In [13]:
duckdb.sql("""
SELECT *
FROM df
WHERE Load_Type = 'Medium_Load'
OR Load_Type = 'Maximum_Load'
ORDER BY Usage_kWh DESC
""").df()

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_of_week,Load_Type
0,22/11/2018 09:45,157.18,77.72,0.00,0.07,89.64,100.0,35100,Weekday,Thursday,Medium_Load
1,15/01/2018 13:45,153.14,70.45,0.00,0.07,90.85,100.0,49500,Weekday,Monday,Medium_Load
2,27/11/2018 11:00,151.67,69.73,0.00,0.07,90.86,100.0,39600,Weekday,Tuesday,Maximum_Load
3,23/03/2018 09:15,151.31,65.20,0.00,0.07,91.84,100.0,33300,Weekday,Friday,Medium_Load
4,18/01/2018 17:30,149.65,64.87,0.00,0.07,91.75,100.0,63000,Weekday,Thursday,Maximum_Load
...,...,...,...,...,...,...,...,...,...,...,...
16963,29/09/2018 23:00,2.59,4.61,0.00,0.00,48.98,100.0,82800,Weekend,Saturday,Medium_Load
16964,21/09/2018 22:30,2.59,4.57,0.00,0.00,49.31,100.0,81000,Weekday,Friday,Medium_Load
16965,18/08/2018 22:30,2.59,4.57,0.00,0.00,49.31,100.0,81000,Weekend,Saturday,Medium_Load
16966,21/09/2018 22:15,2.52,4.21,0.11,0.00,51.36,99.9,80100,Weekday,Friday,Medium_Load
16967,21/09/2018 22:45,2.52,4.61,0.00,0.00,47.97,100.0,81900,Weekday,Friday,Medium_Load

In [14]:
df["Load_Type"].unique()

<ArrowStringArray>
['Light_Load', 'Medium_Load', 'Maximum_Load']
Length: 3, dtype: str

In [17]:
duckdb.sql("""
SELECT 
    Load_Type,
    AVG(Usage_kWh) AS avg_usage_kwh
FROM df
GROUP BY Load_Type
ORDER BY avg_usage_kwh DESC
""").df()

      Load_Type  avg_usage_kwh
0  Maximum_Load      59.265314
1   Medium_Load      38.445394
2    Light_Load       8.626207

In [18]:
duckdb.sql("""
SELECT
    Load_Type,
    COUNT(*) AS n_observations,
    AVG(Usage_kWh) AS avg_usage_kwh,
    MIN(Usage_kWh) AS min_usage_kwh,
    MAX(Usage_kWh) AS max_usage_kwh
FROM df
GROUP BY Load_Type
ORDER BY avg_usage_kwh DESC
""").df()

      Load_Type  n_observations  avg_usage_kwh  min_usage_kwh  max_usage_kwh
0  Maximum_Load            7272      59.265314           2.92         151.67
1   Medium_Load            9696      38.445394           2.52         157.18
2    Light_Load           18072       8.626207           0.00         140.29

In [19]:
duckdb.sql("""
SELECT 
    Day_of_week,
    AVG(Usage_kWh) as avg_usage_kwh
FROM df
GROUP BY Day_of_week
ORDER BY avg_usage_kwh DESC
""").df()

  Day_of_week  avg_usage_kwh
0    Thursday      35.112083
1     Tuesday      34.427614
2      Friday      33.195014
3      Monday      33.143935
4   Wednesday      32.254235
5    Saturday      15.919020
6      Sunday       7.545633

In [21]:
duckdb.sql("""
SELECT
    WeekStatus,
    COUNT(*) AS n_observations,
    AVG(Usage_kWh) AS avg_usage_kwh
FROM df
GROUP BY WeekStatus
ORDER BY avg_usage_kwh DESC
""").df()

  WeekStatus  n_observations  avg_usage_kwh
0    Weekday           25056      33.624727
1    Weekend            9984      11.732327

In [22]:
duckdb.sql("""
SELECT
    Load_Type,
    AVG(Usage_kWh) AS avg_usage_kwh
FROM df
GROUP BY Load_Type
HAVING AVG(Usage_kWh) > 50
ORDER BY avg_usage_kwh DESC
""").df()

      Load_Type  avg_usage_kwh
0  Maximum_Load      59.265314

In [24]:
duckdb.sql("""
SELECT
    CASE
        WHEN Usage_kWh < 25 THEN 'Low'
        WHEN Usage_kWh < 75 THEN 'Medium'
        ELSE 'High'
    END AS usage_category,
    AVG(Usage_kWh) as avg_usage_kwh,
    COUNT(*) AS observations
FROM df
GROUP BY usage_category
ORDER BY avg_usage_kwh
""").df()

  usage_category  avg_usage_kwh  observations
0            Low       4.062258         21448
1         Medium      50.669828          9782
2           High      98.912635          3810

In [26]:
duckdb.sql("""
SELECT
    Load_Type,
    AVG(Usage_kWh) as avg_usage_kwh
FROM df
GROUP BY Load_Type
HAVING AVG(Usage_kWh) > 50
ORDER BY avg_usage_kwh DESC
""").df()

      Load_Type  avg_usage_kwh
0  Maximum_Load      59.265314

In [27]:
df["Load_Type"].unique()

<ArrowStringArray>
['Light_Load', 'Medium_Load', 'Maximum_Load']
Length: 3, dtype: str

In [34]:
Load_info = pd.DataFrame({
    "Load_Type": [
        'Light_Load',
        'Medium_Load',
        'Maximum_Load'
    ],
    "Load_Priority": [
        1,
        2,
        3
    ]
})

In [36]:
duckdb.sql("""
SELECT
    df.Usage_kWh,
    df.Load_Type,
    Load_info.Load_Priority
FROM df
INNER JOIN Load_info
    ON df.Load_Type = Load_info.Load_Type
LIMIT 20
""").df()

    Usage_kWh   Load_Type  Load_Priority
0        3.17  Light_Load              1
1        4.00  Light_Load              1
2        3.24  Light_Load              1
3        3.31  Light_Load              1
4        3.82  Light_Load              1
5        3.28  Light_Load              1
6        3.60  Light_Load              1
7        3.60  Light_Load              1
8        3.28  Light_Load              1
9        3.78  Light_Load              1
10       3.46  Light_Load              1
11       3.24  Light_Load              1
12       3.96  Light_Load              1
13       3.31  Light_Load              1
14       3.31  Light_Load              1
15       3.89  Light_Load              1
16       3.28  Light_Load              1
17       3.56  Light_Load              1
18       3.74  Light_Load              1
19       3.31  Light_Load              1

In [37]:
duckdb.sql("""
SELECT
    df.Usage_kWh,
    df.Load_Type,
    Load_info.Load_Priority
FROM df
LEFT JOIN Load_info
    ON df.Load_Type = Load_info.Load_Type
LIMIT 20
""").df()

    Usage_kWh   Load_Type  Load_Priority
0        3.17  Light_Load              1
1        4.00  Light_Load              1
2        3.24  Light_Load              1
3        3.31  Light_Load              1
4        3.82  Light_Load              1
5        3.28  Light_Load              1
6        3.60  Light_Load              1
7        3.60  Light_Load              1
8        3.28  Light_Load              1
9        3.78  Light_Load              1
10       3.46  Light_Load              1
11       3.24  Light_Load              1
12       3.96  Light_Load              1
13       3.31  Light_Load              1
14       3.31  Light_Load              1
15       3.89  Light_Load              1
16       3.28  Light_Load              1
17       3.56  Light_Load              1
18       3.74  Light_Load              1
19       3.31  Light_Load              1

In [40]:
duckdb.sql("""
WITH load_summary AS (
    SELECT
        Load_Type,
        AVG(Usage_kWh) AS avg_usage_kwh,
        COUNT(*) AS observations
    FROM df
    GROUP BY Load_Type
)

SELECT *
FROM load_summary
WHERE avg_usage_kwh > 50
ORDER BY avg_usage_kwh DESC
""").df()

      Load_Type  avg_usage_kwh  observations
0  Maximum_Load      59.265314          7272

In [42]:
duckdb.sql("""
SELECT 
    Load_Type,
    Usage_kWh,
    AVG(Usage_kWh) OVER (
        PARTITION By Load_Type
    ) AS load_type_avg
FROM df
LIMIT 20
""").df()

      Load_Type  Usage_kWh  load_type_avg
0   Medium_Load      57.85      38.445394
1   Medium_Load      61.88      38.445394
2   Medium_Load      58.75      38.445394
3   Medium_Load      69.37      38.445394
4   Medium_Load      11.48      38.445394
5   Medium_Load       6.59      38.445394
6   Medium_Load       6.80      38.445394
7   Medium_Load       6.66      38.445394
8   Medium_Load      69.77      38.445394
9   Medium_Load      59.76      38.445394
10  Medium_Load      52.02      38.445394
11  Medium_Load      30.31      38.445394
12  Medium_Load      31.93      38.445394
13  Medium_Load      39.31      38.445394
14  Medium_Load      35.06      38.445394
15  Medium_Load      44.42      38.445394
16  Medium_Load      40.18      38.445394
17  Medium_Load      73.62      38.445394
18  Medium_Load      94.86      38.445394
19  Medium_Load      74.56      38.445394

In [43]:
duckdb.sql("""
SELECT 
    Load_Type,
    Usage_kWh,
    ROW_NUMBER() OVER(
        PARTITION BY Load_Type
        ORDER BY Usage_kWh DESC
    ) AS usage_rank
FROM df
""").df()

         Load_Type  Usage_kWh  usage_rank
0      Medium_Load     157.18           1
1      Medium_Load     153.14           2
2      Medium_Load     151.31           3
3      Medium_Load     149.18           4
4      Medium_Load     147.46           5
...            ...        ...         ...
35035   Light_Load       3.02       12284
35036   Light_Load       3.02       12285
35037   Light_Load       3.02       12286
35038   Light_Load       3.02       12287
35039   Light_Load       3.02       12288

[35040 rows x 3 columns]

In [44]:
con = duckdb.connect("steel_energy.duckdb")

In [46]:
con.sql("""
CREATE OR REPLACE TABLE energy_usage AS
SELECT *
FROM df
""")

In [49]:
con.sql("""
SELECT
    Load_Type,
    AVG(Usage_kWh) AS avg_usage_kwh
FROM energy_usage
GROUP BY Load_Type
ORDER BY avg_usage_kwh DESC
""").df()

      Load_Type  avg_usage_kwh
0  Maximum_Load      59.265314
1   Medium_Load      38.445394
2    Light_Load       8.626207